apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
components:
- ../../components
labels:
- includeSelectors: true
  pairs:
    app: hello
images:
- name: image-name
  newName: synerkevin/helloservice
  newTag: v0.1.2
patches:
- patch: |
    - op: replace
      path: /metadata/name
      value: hello
  target:
    kind: Deployment
    name: microservice
- patch: |-
    - op: replace
      path: /metadata/name
      value: hello
  target:
    kind: Service
    name: service-name