apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
components:
- ../../components
labels:
- includeSelectors: true
  pairs:
    app: poker
images:
- name: synerkevin/image-app
  newName: synerkevin/test
  newTag: 33154acc34ac13e97a49412d76f7a63a10a53775