apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
components:
- ../../components
labels:
- includeSelectors: true
  pairs:
    app: poker
images:
- name: image-name
  newName: synerkevin/exogithubactions
  newTag: v0.1.10
patches:
- patch: |
    - op: replace
      path: /metadata/name
      value: poker
  target:
    kind: Deployment
    name: microservice
- patch: |-
    - op: replace
      path: /metadata/name
      value: poker
  target:
    kind: Service
    name: service-name