apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata: 
  name: deploy-dev-template
spec: 
  entrypoint: deploy
  templates:
  - name: deploy
    inputs:
      artifacts:
        - name: folder
          path: /src
      parameters:
      - name: image
      - name: tag
      - name: env
      - name: git-token
        valueFrom:
          configMapKeyRef:
            name: github-cm
            key: token
    script:
      image: kevpoirier/devops-container
      command: [sh]
      source: |
        echo "🔁 Starting deploy workflow"
        cd /src/microservices/overlays/{{inputs.parameters.env}} || exit 1
        echo "📍 Now in: $(pwd)"
        ls -al
        kustomize edit set image synerkevin/exogithubactions={{inputs.parameters.image}}:{{inputs.parameters.tag}}
        echo "🧾 Updated kustomization.yaml:"
        cat kustomization.yaml
        git config user.name "kevpoirier"
        git config user.email "kevin.poirier@synerglass-soft.com"
        git add kustomization.yaml
        git commit -m "Updating {{inputs.parameters.image}} image tag to {{inputs.parameters.tag}}"
        git push "https://{{inputs.parameters.git-token}}@github.com/KevPoirier/gitops.git" HEAD:main