apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: poker
  name: poker
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poker
  template:
    metadata:
      labels:
        app: poker
    spec:
      imagePullSecrets:
        - name: docker-cred
      containers:
        - name: poker
          image: image-name:image-tag
          ports:
            - containerPort: 80
              name: webport
      restartPolicy: Always