apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: microservice
      spec:
        replicas: 1
  - patch: |
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
            value: "5"
    target:
      kind: Deployment
      name: microservice
  - patch: |
      - op: replace
        path: /spec/template/spec/affinity
        value:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: mode
                    operator: In
                    values:
                    - microservice
    target:
      kind: Deployment
      name: microservice
            